
version: '3'
services:
  api:
    image: api-impl:1.0
    ports:
        - "127.0.0.1:8080:8080"
    links:
        - postgres
    environment:
        spring_datasource_url: jdbc:postgresql://postgres:5432/katanox_test
    networks:
        - backend

  postgres:
    image: postgres:13.5
    container_name: katanox_test_db
    environment:
      - POSTGRES_USER=katanox-user
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=katanox_test
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  postgres:
    driver: local

networks:
  backend:
    driver: bridge
